import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_FALLBACK = {"ai_likelihood": 0.5, "confidence": 0.5, "explanation": "signal unavailable"}

_SYSTEM_PROMPT = (
    "You are an expert forensic linguist. Analyze the submitted text and assess the likelihood "
    "that it was generated by an AI model rather than written by a human. Evaluate writing style, "
    "internal consistency, phrasing patterns, tone, and any telltale signs of AI generation. "
    "Respond ONLY with a single valid JSON object — no markdown, no prose, no extra keys — "
    "in exactly this format:\n"
    '{"ai_likelihood": <float 0.0–1.0>, "confidence": <float 0.0–1.0>, "explanation": "<short string>"}'
)


def groq_signal(text: str) -> dict:
    try:
        client = Groq(api_key=os.environ["GROQ_API_KEY"])
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            max_tokens=256,
        )
        raw = response.choices[0].message.content.strip()
        result = json.loads(raw)
        return {
            "ai_likelihood": float(result["ai_likelihood"]),
            "confidence": float(result["confidence"]),
            "explanation": str(result["explanation"]),
        }
    except (json.JSONDecodeError, KeyError, ValueError):
        return {**_FALLBACK, "explanation": "parse failure — model returned unexpected format"}
    except Exception:
        return {**_FALLBACK, "explanation": "api error — signal unavailable"}
